# Generated by Django 5.2.6 on 2025-10-21 20:28

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Publicado em: ')),
                ('imagem', cloudinary.models.CloudinaryField(max_length=255, verbose_name='images')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postagens.perfil')),
                ('favoritos', models.ManyToManyField(blank=True, related_name='postagens_favoritos', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='postagens_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtagnome', models.CharField(blank=True, max_length=50, null=True)),
                ('hashtaquant', models.IntegerField(blank=True, null=True)),
                ('tempo', models.DateTimeField(auto_now_add=True)),
                ('dia', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='postagens.perfil')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='postagens.postagem')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Publicado em: ')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postagens.perfil')),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postagens.postagem')),
            ],
        ),
    ]
