# Generated by Django 5.2.6 on 2025-10-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergia', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='alergia',
            field=models.ManyToManyField(blank=True, to='postagens.alergias'),
        ),
        migrations.AddField(
            model_name='postagem',
            name='alergia',
            field=models.ManyToManyField(blank=True, to='postagens.alergias'),
        ),
    ]
