# Generated by Django 5.2.6 on 2025-09-24 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0002_postagens_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postagens.postagens')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postagens.perfil')),
            ],
        ),
    ]
