# Generated by Django 5.2.6 on 2025-09-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0003_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Publicado em: '),
        ),
        migrations.AlterField(
            model_name='postagens',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Publicado em: '),
        ),
    ]
