# Generated by Django 5.2.6 on 2025-09-25 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0004_alter_comentario_data_alter_postagens_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postagens',
            new_name='postagem',
        ),
    ]
