# Generated by Django 5.2.6 on 2025-09-26 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0009_postagem_like_postagem_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='like',
        ),
    ]
