# Generated by Django 5.2.6 on 2025-09-26 21:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0010_remove_postagem_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='postagens_favoritos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='postagens_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
