# Generated by Django 5.2.7 on 2025-10-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0012_alter_postagem_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
