# Generated by Django on behalf of assistant

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0012_alter_postagem_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtagnome', models.CharField(max_length=50, null=True, blank=True)),
                ('hashtaquant', models.IntegerField(null=True, blank=True)),
                ('tempo', models.DateTimeField(auto_now_add=True)),
                ('dia', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postagens.postagem', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postagens.perfil', null=True)),
            ],
        ),
    ]
