name: Testes automatizados do Wondercooking

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev python3-dev

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências do projeto
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Migrações no Neon
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
          DEBUG: 'False'
        run: |
          python manage.py migrate

      - name: Testes
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
          DEBUG: 'False'
        run: |
          python manage.py test
